apiVersion: v1
kind: ConfigMap
metadata:
  name: system
  namespace: substratus
data:
  CLOUD: kind
  CLUSTER_NAME: substratus
  ARTIFACT_BUCKET_URL: tar:///bucket
  REGISTRY_URL: http://docker.svc.cluster.local:5000
