apiVersion: apps/v1
kind: Deployment
metadata:
  name: sci-gcp
  namespace: substratus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sci-gcp
  template:
    metadata:
      labels:
        app: sci-gcp
    spec:
      serviceAccountName: sci-gcp
      terminationGracePeriodSeconds: 10
      containers:
        - name: sci-gcp
          # use this when running via skaffold
          # image: us-central1-docker.pkg.dev/substratus-ai-001/substratus/gcpmanager:latest
          image: sci-gcp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10080
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 10080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
