apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-40b-instruct
spec:
  source:
    git:
      url: https://github.com/substratusai/model-falcon-40b-instruct
  size:
    parameterBits: 8
    parameterCount: 40000000000
  compute:
    types: ["GPU"]
