apiVersion: substratus.ai/v1
kind: Server
metadata:
  name: falcon-7b-instruct-k8s
spec:
  image:
    git:
      url: https://github.com/substratusai/model-server-basaran
  model:
    name: falcon-7b-instruct-k8s
  resources:
    gpu:
      type: nvidia-l4
      count: 1
