apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-7b-instruct-squad
spec:
  container:
    git:
      url: https://github.com/substratusai/model-trainer-huggingface
  trainer:
    baseModel:
      name: falcon-7b-instruct
    dataset:
      name: squad
    epochs: 1
  resources:
    cpu:
      count: 4
      memory: 8
    gpu:
      count: 4
      type: nvidia-l4
