apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-7b-instruct-k8s-custom-prompt
spec:
  image:
    name: substratusai/model-trainer-huggingface
  baseModel:
    name: falcon-7b-instruct
  trainingDataset:
    name: k8s-instructions
  params:
    num_train_epochs: 1
    # Save to checkpoint every 5 steps
    save_steps: 5
    prompt_template: |
      You're a helpful assistant that helps with generating K8s YAML manifests. Your responses should only be YAML or multi YAML files
      ## Instruction
      {prompt}
      ## Response:
      {completion}
  resources:
    gpu:
      count: 4
      type: nvidia-l4
