apiVersion: substratus.ai/v1
kind: Server
metadata:
  name: falcon-7b-instruct-k8s
spec:
  image: substratusai/model-server-basaran
  model:
    name: falcon-7b-instruct-k8s
  resources:
    gpu:
      type: nvidia-l4
      count: 1
