apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-7b-instruct-k8s
spec:
  source:
    modelName: falcon-7b-instruct
  training:
    datasetName: k8s-instructions
    params:
      epochs: 1
  size:
    parameterBits: 16
    parameterCount: 7000000000
  compute:
    types: ["GPU"]
