apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-7b-instruct-k8s
spec:
  image:
    name: substratusai/model-trainer-huggingface:pr-16
  baseModel:
    name: falcon-7b-instruct
  trainingDataset:
    name: k8s-instructions
  params:
    # num_train_epochs: 1
    max_steps: 5
  resources:
    gpu:
      count: 4
      type: nvidia-l4
