apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-7b-instruct
spec:
  source:
    git:
      url: github.com/substratusai/model-falcon-7b-instruct
  size:
    parameterBits: 16
    parameterCount: 7000000000
  compute:
    types: ["GPU"]
