apiVersion: substratus.ai/v1
kind: Notebook
metadata:
  name: falcon-7b-instruct
spec:
  command: ["notebook.sh"]
  suspend: false
  image:
    # TODO(bjb): validate that name and upload aren't specified together
    # name: substratusai/model-trainer-huggingface
    upload:
      # md5checksum: 38d6a014d78f1de1ba0b10ca34d29778
      md5checksum: 38d6a014d78f1de1ba0b10ca34d29779
  model:
    name: falcon-7b-instruct
  dataset:
    name: k8s-instructions
  resources:
    disk: 50
    # gpu:
    #   type: nvidia-l4
    #   count: 4
