apiVersion: substratus.ai/v1
kind: Notebook
metadata:
  name: falcon-7b-instruct
spec:
  command: ["notebook.sh"]
  suspend: true
  image:
    git:
      url: https://github.com/substratusai/model-trainer-huggingface
  model:
    name: falcon-7b-instruct
  dataset:
    name: k8s-instructions
  resources:
    cpu: 4
    memory: 10
    disk: 50
    gpu:
      type: nvidia-l4
      count: 4
