apiVersion: substratus.ai/v1
kind: Notebook
metadata:
  name: falcon-7b-instruct
spec:
  command: ["notebook.sh"]
  suspend: false
  build:
    git:
      url: https://github.com/substratusai/images
      path: model-trainer-huggingface
  model:
    name: falcon-7b-instruct
  dataset:
    name: k8s-instructions
  resources:
    disk: 50
    gpu:
      type: nvidia-l4
      count: 4
