apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-40b
spec:
  image:
    git:
      url: https://github.com/substratusai/images
      path: model-loader-huggingface
  params:
    name: tiiuae/falcon-40b
