apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-40b-k8s
spec:
  image: substratusai/model-trainer-huggingface
  model:
    name: falcon-40b
  dataset:
    name: k8s-instructions
  params:
    epochs: 1
  resources:
    gpu:
      count: 8
      type: nvidia-l4
