apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: falcon-40b
spec:
  source:
    git:
      url: https://github.com/substratusai/model-falcon-40b
  size:
    parameterBits: 16
    parameterCount: 40000000000
  compute:
    types: ["GPU"]
