apiVersion: substratus.ai/v1
kind: Server
metadata:
  name: falcon-40b
spec:
  image:
    git:
      url: https://github.com/substratusai/images
      path: model-server-basaran
  model:
    name: falcon-40b
  resources:
    gpu:
      type: nvidia-l4
      count: 4