apiVersion: substratus.ai/v1
kind: Server
metadata:
  name: falcon-40b
spec:
  image: substratusai/model-server-basaran
  model:
    name: falcon-40b
  env:
    MODEL_LOAD_IN_4BIT: "true"
  resources:
    gpu:
      type: nvidia-l4
      count: 1
