apiVersion: substratus.ai/v1
kind: Dataset
metadata:
  name: k8s-instructions
spec:
  filename: k8s-instructions.jsonl
  source:
    git:
      url: https://github.com/substratusai/dataset-k8s-instructions
