apiVersion: substratus.ai/v1
kind: Dataset
metadata:
  name: k8s-instructions
spec:
  params:
    urls: https://huggingface.co/datasets/substratusai/k8s-instructions/raw/main/k8s-instructions.jsonl
  image:
    git:
      url: https://github.com/substratusai/images
      path: dataset-loader-http
