apiVersion: v1
kind: Namespace
metadata:
  name: substratus
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: substratus
    app.kubernetes.io/part-of: substratus
    app.kubernetes.io/managed-by: kustomize