apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: llama-2-7b
spec:
  image: substratusai/model-loader-huggingface
  params:
    name: meta-llama/Llama-2-7b-hf
    hugging_face_hub_token: ${HUGGINGFACE_TOKEN}
