apiVersion: substratus.ai/v1
kind: Notebook
metadata:
  name: facebook-opt-125m
spec:
  command: ["notebook.sh"]
  suspend: true
  image:
    git:
      url: https://github.com/substratusai/images
      path: base
  model:
    name: facebook-opt-125m
  dataset:
    name: squad
  params:
    foo: bar
    x: 123
