apiVersion: substratus.ai/v1
kind: Server
metadata:
  name: facebook-opt-125m
spec:
  image:
    git:
      url: https://github.com/substratusai/images
      path: model-server-basaran
  model:
    name: facebook-opt-125m
