apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: my-model
spec:
  version: v1.0.0
  source:
    modelName: facebook-opt-125m
  training:
    datasetName: favorite-colors
  # TODO: This should be copied from the source Model.
  size:
    parameterBits: 32
    parameterCount: 125000000
