apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: fb-opt-125m-squad
spec:
  build:
    git:
      url: https://github.com/substratusai/images
      path: model-trainer-huggingface
  model:
    name: facebook-opt-125m
  dataset:
    name: squad
  params:
    epochs: 1
