apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: fb-opt-125m-squad
spec:
  container:
    git:
      url: https://github.com/substratusai/model-trainer-huggingface
  trainer:
    model:
      name: facebook-opt-125m
    dataset:
      name: squad
    epochs: 1
  resources:
    cpu:
      count: 4
      memory: 4
