apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: fb-opt-125m-k8s-instructions
spec:
  source:
    modelName: facebook-opt-125m
  training:
    datasetName: k8s-instructions
    params:
      epochs: 1
  size:
    parameterBits: 32
    parameterCount: 125000000
  compute:
    types: ["CPU", "GPU"]
