apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: facebook-opt-125m
spec:
  source:
    git:
      url: https://github.com/substratusai/model-facebook-opt-125m
      branch: main
  size:
    parameterBits: 32
    parameterCount: 125000000
  compute:
    types: ["CPU", "GPU"]
