apiVersion: substratus.ai/v1
kind: ModelServer
metadata:
  name: facebook-opt-125m
spec:
  command: ["serve.sh"]
  image:
    git:
      url: https://github.com/substratusai/model-server-basaran
  model:
    name: facebook-opt-125m
