name: goreleaser
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - id: build-open-notebook
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -f kubectl/open-notebook/.goreleaser.yaml
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: kubectl-open-notebook-plugin
          path: |
            dist/*
            !dist/artifacts.json
            !dist/metadata.yaml
            !dist/config.yaml
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
